"""update apps table

Revision ID: c16096306eee
Revises: dc86568cd7ff
Create Date: 2026-09-06 19:49:02.975013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c16096306eee'
down_revision: Union[str, Sequence[str], None] = 'dc86568cd7ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apps', sa.Column('app_name', sa.String(), nullable=False))
    op.add_column('apps', sa.Column('category', sa.String(), nullable=False))
    op.add_column('apps', sa.Column('developer', sa.String(), nullable=False))
    op.add_column('apps', sa.Column('rating', sa.Float(), nullable=True))
    op.add_column('apps', sa.Column('downloads', sa.BigInteger(), nullable=True))
    op.add_column('apps', sa.Column('monthly_price', sa.Float(), nullable=True))
    op.add_column('apps', sa.Column('yearly_price', sa.Float(), nullable=True))
    op.add_column('apps', sa.Column('currency', sa.String(), nullable=True))
    op.add_column('apps', sa.Column('free_trial_days', sa.Integer(), nullable=True))
    op.add_column('apps', sa.Column('pricing_type', sa.String(), nullable=False))
    op.add_column('apps', sa.Column('pricing_source', sa.String(), nullable=False))
    op.add_column('apps', sa.Column('pricing_date', sa.Date(), nullable=False))
    op.add_column('apps', sa.Column('pricing_status', sa.String(), nullable=False))
    op.add_column('apps', sa.Column('normalized_monthly_price', sa.Float(), nullable=True))
    op.add_column('apps', sa.Column('normalized_yearly_price', sa.Float(), nullable=True))
    op.add_column('apps', sa.Column('annualized_monthly_cost', sa.Float(), nullable=True))
    op.add_column('apps', sa.Column('annual_savings', sa.Float(), nullable=True))
    op.add_column('apps', sa.Column('annual_discount_pct', sa.Float(), nullable=True))
    op.add_column('apps', sa.Column('downloads_numeric', sa.Float(), nullable=True))
    op.add_column('apps', sa.Column('log_downloads', sa.Float(), nullable=True))
    op.add_column('apps', sa.Column('popularity_score', sa.Float(), nullable=True))
    op.add_column('apps', sa.Column('rating_score', sa.Float(), nullable=True))
    op.add_column('apps', sa.Column('engagement_score', sa.Float(), nullable=True))
    op.add_column('apps', sa.Column('price_tier', sa.String(), nullable=True))
    op.add_column('apps', sa.Column('has_free_trial', sa.Boolean(), nullable=True))
    op.add_column('apps', sa.Column('is_freemium', sa.Boolean(), nullable=True))
    op.add_column('apps', sa.Column('is_verified_price', sa.Boolean(), nullable=True))
    op.add_column('apps', sa.Column('price_adjusted_value_score', sa.Float(), nullable=True))
    op.drop_column('apps', 'price')
    op.drop_column('apps', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apps', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('apps', sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('apps', 'price_adjusted_value_score')
    op.drop_column('apps', 'is_verified_price')
    op.drop_column('apps', 'is_freemium')
    op.drop_column('apps', 'has_free_trial')
    op.drop_column('apps', 'price_tier')
    op.drop_column('apps', 'engagement_score')
    op.drop_column('apps', 'rating_score')
    op.drop_column('apps', 'popularity_score')
    op.drop_column('apps', 'log_downloads')
    op.drop_column('apps', 'downloads_numeric')
    op.drop_column('apps', 'annual_discount_pct')
    op.drop_column('apps', 'annual_savings')
    op.drop_column('apps', 'annualized_monthly_cost')
    op.drop_column('apps', 'normalized_yearly_price')
    op.drop_column('apps', 'normalized_monthly_price')
    op.drop_column('apps', 'pricing_status')
    op.drop_column('apps', 'pricing_date')
    op.drop_column('apps', 'pricing_source')
    op.drop_column('apps', 'pricing_type')
    op.drop_column('apps', 'free_trial_days')
    op.drop_column('apps', 'currency')
    op.drop_column('apps', 'yearly_price')
    op.drop_column('apps', 'monthly_price')
    op.drop_column('apps', 'downloads')
    op.drop_column('apps', 'rating')
    op.drop_column('apps', 'developer')
    op.drop_column('apps', 'category')
    op.drop_column('apps', 'app_name')
    # ### end Alembic commands ###
